/**
 * lookupSeedCatalogueKeys — SEED-KEYS-EN-1: the English translation-KEY NAMES for
 * every LABEL_KEYED seed label (see lookupSeedCatalogue.ts). The label -> old Dutch
 * camelCase key was itself Dutch (e.g. `functions.logistiekMedewerker`); this map
 * gives the same lookup an English key name, derived by `labelKey()` (lookupSeedI18n.ts)
 * from the EN translation of that same seed. Values (translations in every locale) are
 * unchanged — only the key NAME moved. Generated 29-09 from src/i18n/locales/{nl,en}/
 * common.json by e2e/probe-lookups.mjs's regeneration rule (see that file's header):
 * for each SEED_LABELS[family] entry, newKey = labelKey(en value); a collision (two
 * Dutch labels sharing one English translation, e.g. "doorverwijzing"/"referral" both
 * -> "Referral") is broken by seed order, appending _2/_3.
 *
 * Keyed by the DUTCH SEED LABEL (not the old key), because seedKeyFor() looks this up
 * from item.label before falling back to labelKey(label) for anything not in the map
 * (a tenant-created value, or a family added after this map was generated).
 */

// family -> Dutch seed label -> English translation key.
export const SEED_LABEL_KEYS: Record<string, Record<string, string>> = {
  candidateSources: {
    "Careersite": "careersite",
    "Doorverwijzing": "referral",
    "Facebook": "facebook",
    "Indeed": "indeed",
    "Inloop": "walkIn",
    "LinkedIn": "linkedin",
    "referral": "referral_2",
    "walk_in": "walkIn_2",
    "Website": "website",
    "werkzoeken": "werkzoeken",
    "Werkzoeken.nl": "werkzoekenNl",
  },
  channels: {
    "Carrière-pagina": "careerSite",
    "Google Jobs": "googleJobs",
    "Indeed": "indeed",
    "Werkzoeken": "werkzoeken",
  },
  contactFunctions: {
    "Administratie": "administration",
    "Directeur": "director",
    "HR-manager": "hrManager",
    "Locatiemanager": "locationManager",
    "Operationeel manager": "operationsManager",
    "Planner": "planner",
    "Recruiter": "recruiter",
    "Teamleider": "teamLeader",
  },
  customerSources: {
    "LinkedIn": "linkedin",
    "Google": "google",
    "Website leads": "websiteLeads",
  },
  documentTypes: {
    "Bankpas privé": "privateBankCard",
    "Bankpas zakelijk": "businessBankCard",
    "Certificaat": "certificate",
    "Contract": "contract",
    "CV": "cv",
    "Diploma": "diploma",
    "Foto": "photo",
    "ID-bewijs": "idDocument",
    "Overig": "other",
    "VOG": "certificateOfConductVOG",
  },
  driverLicenses: {
    "A": "a",
    "A1": "a1",
    "A2": "a2",
    "AM": "am",
    "B": "b",
    "BE": "be",
    "C": "c",
    "C1": "c1",
    "C1E": "c1e",
    "CE": "ce",
    "D": "d",
    "D1": "d1",
    "D1E": "d1e",
    "DE": "de",
    "T": "t",
  },
  educationLevels: {
    "Basisonderwijs": "primaryEducation",
    "HAVO": "havo",
    "HBO": "hbo",
    "HBO-master": "hboMaster",
    "MBO": "mbo",
    "MBO-1": "mbo1",
    "MBO-2": "mbo2",
    "MBO-3": "mbo3",
    "MBO-4": "mbo4",
    "VMBO": "vmbo",
    "VWO": "vwo",
    "WO": "wo",
    "WO-master": "woMaster",
  },
  escalationReasons: {
    "Boos": "angry",
    "Ongeluk": "accident",
    "Overig": "other",
    "Overlijden": "bereavement",
    "Uitschrijven": "deregistration",
    "Ziek": "sick",
  },
  functions: {
    "Barman/Barvrouw": "bartender",
    "Bedieningsmedewerker": "waitingStaff",
    "Begeleider GHZ": "supportWorkerDisabilityCare",
    "Beveiliger": "securityGuard",
    "Cateringmedewerker": "cateringAssistant",
    "Chauffeur CE": "ceDriver",
    "Doktersassistent": "doctorSAssistant",
    "Evenementbeveiliger": "eventSecurityGuard",
    "EVV'er": "independentNursingCarer",
    "Gastheer/Gastvrouw": "host",
    "Heftruckchauffeur": "forkliftDriver",
    "Helpende": "careAssistant",
    "Helpende Plus": "careAssistantPlus",
    "Inpakker": "packer",
    "Kok": "cook",
    "Logistiek medewerker": "logisticsEmployee",
    "Magazijnmedewerker": "warehouseOperative",
    "Mobiel surveillant": "mobilePatrolOfficer",
    "Objectbeveiliger": "siteSecurityGuard",
    "Orderpicker": "orderPicker",
    "Receptiebeveiliger": "receptionSecurityGuard",
    "Surveillant": "patrolOfficer",
    "Teamleider warehouse": "warehouseTeamLeader",
    "Verpleegkundige N4": "nurseN4",
    "Verpleegkundige N5": "nurseN5",
    "Verzorgende IG": "careWorkerIG",
    "Wijkverpleegkundige": "communityNurse",
    "Zelfstandig werkend kok": "independentCook",
  },
  industries: {
    "Administratie": "administration",
    "Bouw": "construction",
    "Financiën": "finance",
    "Horeca": "hospitality",
    "IT": "it",
    "Logistiek": "logistics",
    "Onderwijs": "education",
    "Overig": "other",
    "Productie": "manufacturing",
    "Retail": "retail",
    "Techniek": "engineering",
    "Uitzendbureau": "staffingAgency",
    "Werving": "recruitment",
    "Zorg": "healthcare",
  },
  languageLevels: {
    "Goed": "good",
    "Matig": "fair",
    "Moedertaal": "native",
    "Slecht": "poor",
    "Zeer goed": "veryGood",
  },
  languages: {
    "Arabisch": "arabic",
    "Duits": "german",
    "Engels": "english",
    "Frans": "french",
    "Italiaans": "italian",
    "Nederlands": "dutch",
    "Oekraïens": "ukrainian",
    "Papiaments": "papiamento",
    "Pools": "polish",
    "Portugees": "portuguese",
    "Roemeens": "romanian",
    "Spaans": "spanish",
    "Turks": "turkish",
  },
  nationalities: {
    "Antilliaans": "antillean",
    "Belgisch": "belgian",
    "Brits": "british",
    "Bulgaars": "bulgarian",
    "Duits": "german",
    "Eritrees": "eritrean",
    "Frans": "french",
    "Grieks": "greek",
    "Hongaars": "hungarian",
    "Italiaans": "italian",
    "Marokkaans": "moroccan",
    "Nederlands": "dutch",
    "Oekraïens": "ukrainian",
    "Overig": "other",
    "Pools": "polish",
    "Portugees": "portuguese",
    "Roemeens": "romanian",
    "Somalisch": "somali",
    "Spaans": "spanish",
    "Surinaams": "surinamese",
    "Syrisch": "syrian",
    "Turks": "turkish",
  },
  pools: {
    "Actieve kandidaten": "activeCandidates",
    "Interessant later": "interestingForLater",
    "Top kandidaten": "topCandidates",
    "Warme leads": "warmLeads",
  },
  rejectionReasons: {
    "Andere kandidaat gekozen": "anotherCandidateWasChosen",
    "Geen culturele match": "noCulturalFit",
    "Niet gekwalificeerd": "notQualified",
    "Onvoldoende ervaring": "insufficientExperience",
    "Salariswens te hoog": "salaryExpectationTooHigh",
    "Te grote reisafstand": "commuteTooFar",
    "Teruggetrokken door kandidaat": "withdrawnByCandidate",
  },
  seniorityLevels: {
    "Medior": "midLevel",
    "Professional": "professional",
    "Senior": "senior",
    "Starter": "entryLevel",
  },
  skillLevels: {
    "Basis": "basic",
    "Expert": "expert",
    "Gevorderd": "advanced",
  },
  vacancyStatuses: {
    "Concept": "draft",
    "Gepauzeerd": "paused",
    "Gesloten": "closed",
    "Open": "open",
  },
  workflowFolders: {
    "Kandidaten": "candidates",
    "Sollicitaties": "applications",
    "Matches": "matches",
    "Vacatures": "vacancies",
    "Kansen": "opportunities",
    "Taken": "tasks",
    "Systeemmeldingen": "systemNotifications",
    "Klanten": "customers",
    "Planning": "planning",
    "AVG / Bewaartermijnen": "gdprRetentionPeriods",
    "Rapportage": "reporting",
    "AI Planner": "aiPlanner",
    "AI Recruiter": "aiRecruiter",
    "Koios AI": "koiosAI",
    "Shiftmanager Rapportage": "shiftmanagerReporting",
    "Shiftmanager Automaties": "shiftmanagerAutomations",
    "Koppeling Elanza": "elanzaConnection",
    "Koppeling Aelio": "aelioConnection",
    "Koppeling Intus": "intusConnection",
    "Koppeling SDB": "sdbConnection",
  },
  workflowNames: {
    "Heractivering": "reactivation",
    "Niet benaderd > X dagen": "notApproachedXDays",
    "Verjaardagsfelicitatie": "birthdayGreeting",
    "Afspraakbevestiging": "appointmentConfirmation",
    "HelloFlex-koppeling (per kandidaat)": "helloflexConnectionPerCandidate",
    "HelloFlex-koppeling — bulk": "helloflexConnectionBulk",
    "Shiftmanager-koppeling (per kandidaat)": "shiftmanagerConnectionPerCandidate",
    "Shiftmanager-koppeling — bulk": "shiftmanagerConnectionBulk",
    "Sollicitatiefase → Match": "applicationStageMatch",
    "Afwijzing versturen": "sendRejection",
    "Leads-telling vacatures": "vacancyLeadCount",
    "Match → werkervaring": "matchWorkExperience",
    "Contract loopt af": "contractExpiring",
    "Match loopt af — herinnering kandidaat": "matchExpiringCandidateReminder",
    "Match loopt af — melding eigenaar kandidaat": "matchExpiringNotifyCandidateOwner",
    "Match loopt af — melding eigenaar klant": "matchExpiringNotifyCustomerOwner",
    "Taak bij aflopend klantcontract": "taskOnExpiringCustomerContract",
    "Taak bij lang geen klantcontact": "taskOnLongNoCustomerContact",
    "Taak bij aflopende match bij klant": "taskOnExpiringCustomerMatch",
    "Taak bij vacature lang online zonder resultaat": "taskOnVacancyLongOnlineWithoutResult",
    "Melding bij naderende sluitingsdatum": "notificationOnApproachingClosingDate",
    "Onboarding & evaluatie": "onboardingEvaluation",
    "Nieuwe match — melding": "newMatchNotification",
    "Op matchfase — melding": "onMatchStageNotification",
    "WhatsApp-storing — melding": "whatsappOutageNotification",
    "WhatsApp hersteld — melding": "whatsappRestoredNotification",
    "Afwijzing — melding": "rejectionNotification",
    "Verlopend document — melding": "expiringDocumentNotification",
    "Ontbrekende CV — melding": "missingCVNotification",
    "Onbeantwoord gesprek — melding": "unansweredConversationNotification",
    "Bijna weer beschikbaar — melding": "availableAgainSoonNotification",
    "Bijna weer beschikbaar — taak": "availableAgainSoonTask",
    "Beschikbaarheidsdatum verstreken — melding": "availabilityDatePassedNotification",
    "Beschikbaarheidsdatum verstreken — taak": "availabilityDatePassedTask",
    "Verlof loopt bijna af — melding": "leaveEndingSoonNotification",
    "Verlof loopt bijna af — taak": "leaveEndingSoonTask",
    "Verlofdatum verstreken — melding": "leaveDatePassedNotification",
    "Verlofdatum verstreken — taak": "leaveDatePassedTask",
    "Niet-beschikbaar-periode loopt bijna af — melding": "unavailabilityPeriodEndingSoonNotification",
    "Niet-beschikbaar-periode loopt bijna af — taak": "unavailabilityPeriodEndingSoonTask",
    "Niet-beschikbaar-datum verstreken — melding": "unavailabilityDatePassedNotification",
    "Niet-beschikbaar-datum verstreken — taak": "unavailabilityDatePassedTask",
    "Staat stil op status — melding": "stalledOnStatusNotification",
    "Staat stil op status — taak": "stalledOnStatusTask",
    "Lead staat stil — melding": "leadStalledNotification",
    "Lead staat stil — taak": "leadStalledTask",
    "Lang geen contact → bellijst": "longNoContactCallList",
    "Lang geen contact → WhatsApp check-in": "longNoContactWhatsAppCheckIn",
    "Lang niet gesproken — melding": "longNoConversationNotification",
    "Vraag bewaartoestemming": "askRetentionConsent",
    "Verloop-melding bewaartermijn": "retentionPeriodExpiryNotification",
    "Archiveer bij verlopen bewaartermijn": "archiveOnExpiredRetentionPeriod",
    "Escalatie: dossier staat te lang gearchiveerd": "escalationFileArchivedTooLong",
    "Backoffice mailen bij archivering": "emailBackofficeOnArchiving",
    "AI Planner - Employee status change": "aiPlannerEmployeeStatusChange",
    "AI Planner - Offering Shifts - Actief - NIEUW": "aiPlannerOfferingShiftsActiveNEW",
    "AI Planner - Offering Shifts - Actief": "aiPlannerOfferingShiftsActive",
    "AI Planner - Offering Shifts - Niet actief": "aiPlannerOfferingShiftsNotActive",
    "AI Planner - Offering Shifts - Intake": "aiPlannerOfferingShiftsIntake",
    "AI Planner - ShiftReminder": "aiPlannerShiftReminder",
    "AI Planner - Geen reactie (24-72u)": "aiPlannerNoResponse2472h",
    "AI Planner - Geen reactie escalatie (>72u)": "aiPlannerNoResponseEscalation72h",
    "AI Planner - Worked Shifts": "aiPlannerWorkedShifts",
    "AI Planner - Response": "aiPlannerResponse",
    "AI-recruiter pakt nieuwe sollicitatie op": "aiRecruiterPicksUpANewApplication",
    "Sync alles": "syncAll",
    "Sync kandidaten": "syncCandidates",
    "Sync klanten": "syncCustomers",
    "Sync diensten": "syncShifts",
    "AI Planner De-Escalate": "aiPlannerDeEscalate",
    "SM → Elanza": "smElanza",
    "Elanza → SM": "elanzaSM",
    "Aelio → SM - PRD": "aelioSMPRD",
    "SM → Aelio": "smAelio",
    "Aelio - Check-Out Hours": "aelioCheckOutHours",
    "Aelio FLEX/DETA → SM": "aelioFLEXDETASM",
    "Intus → SM": "intusSM",
    "SM → Intus": "smIntus",
    "Intus → SM Gewerkte diensttijden": "intusSMWorkedShiftTimes",
    "SDB Beschikbaar Mailhook": "sdbAvailableMailhook",
    "SDB Vervallen Mailhook": "sdbExpiredMailhook",
    "SM → SDB Planning": "smSDBPlanning",
    "Nightly kandidaat-verrijking": "nightlyCandidateEnrichment",
    "Koios: verstuur WhatsApp": "koiosSendWhatsApp",
    "Koios: verstuur e-mail": "koiosSendEmail",
    "Koios: maak taak": "koiosCreateTask",
    "Koios: plan afspraak": "koiosScheduleAppointment",
    "Koios: stuur notificatie": "koiosSendNotification",
    "Koios: voeg toe aan bellijst": "koiosAddToCallList",
  },
}
