/**
 * lookupSeedCatalogueWorkflows — the workflow-domain slice of the LOOKUP-I18N-1 seed
 * catalogue. Split out of lookupSeedCatalogue.ts on 2026-08-25 once the combined file
 * crossed the §3 400-line split trigger: workflowFolders/workflowNames is a single,
 * fast-growing family (WorkflowFolderSeeder / TemplateLibrary) with its own write
 * pattern, so hiving it into its own file is a single-purpose split, not a line-count
 * trim. Re-exported into SEED_LABELS by lookupSeedCatalogue.ts — every consumer keeps
 * importing SEED_LABELS/LABEL_KEYED from there, never from this file directly.
 */

// Workflow folders (WorkflowFolderSeeder::FOLDERS) — the fixed folder taxonomy every
// tenant seeds into. LABEL_KEYED: the row carries a stable "key" slug too, but the
// match is deliberately on the LABEL (does it still read as what we seeded), matching
// every other family here — a tenant rename falls through untranslated either way.
const workflowFolders: Record<string, string> = {
  kandidaten: "Kandidaten",
  sollicitaties: "Sollicitaties",
  matches: "Matches",
  vacatures: "Vacatures",
  kansen: "Kansen",
  taken: "Taken",
  systeemmeldingen: "Systeemmeldingen",
  klanten: "Klanten",
  planning: "Planning",
  avgBewaartermijnen: "AVG / Bewaartermijnen",
  rapportage: "Rapportage",
  aiPlanner: "AI Planner",
  aiRecruiter: "AI Recruiter",
  koiosAI: "Koios AI",
  shiftmanagerRapportage: "Shiftmanager Rapportage",
  shiftmanagerAutomaties: "Shiftmanager Automaties",
  koppelingElanza: "Koppeling Elanza",
  koppelingAelio: "Koppeling Aelio",
  koppelingIntus: "Koppeling Intus",
  koppelingSDB: "Koppeling SDB",
}
// Seeded workflow TEMPLATES (TemplateLibrary, all groups) + the one demo-dashboard
// workflow (SeedDemoDashboard::seedWorkflowRuns). LABEL_KEYED for the same reason as
// workflowFolders above.
const workflowNames: Record<string, string> = {
  heractivering: "Heractivering",
  nietBenaderdXDagen: "Niet benaderd > X dagen",
  verjaardagsfelicitatie: "Verjaardagsfelicitatie",
  afspraakbevestiging: "Afspraakbevestiging",
  adresGeocoderenPDOK: "Adres geocoderen (PDOK)",
  adressenGeocoderenBulkPDOK: "Adressen geocoderen — bulk (PDOK)",
  helloflexKoppelingPerKandidaat: "HelloFlex-koppeling (per kandidaat)",
  helloflexKoppelingBulk: "HelloFlex-koppeling — bulk",
  shiftmanagerKoppelingPerKandidaat: "Shiftmanager-koppeling (per kandidaat)",
  shiftmanagerKoppelingBulk: "Shiftmanager-koppeling — bulk",
  sollicitatiefaseMatch: "Sollicitatiefase → Match",
  afwijzingVersturen: "Afwijzing versturen",
  leadsTellingVacatures: "Leads-telling vacatures",
  matchWerkervaring: "Match → werkervaring",
  contractLooptAf: "Contract loopt af",
  matchLooptAfHerinneringKandidaat: "Match loopt af — herinnering kandidaat",
  matchLooptAfMeldingEigenaarKandidaat: "Match loopt af — melding eigenaar kandidaat",
  matchLooptAfMeldingEigenaarKlant: "Match loopt af — melding eigenaar klant",
  taakBijAflopendKlantcontract: "Taak bij aflopend klantcontract",
  taakBijLangGeenKlantcontact: "Taak bij lang geen klantcontact",
  taakBijAflopendeMatchBijKlant: "Taak bij aflopende match bij klant",
  taakBijVacatureLangOnlineZonderResultaat: "Taak bij vacature lang online zonder resultaat",
  meldingBijNaderendeSluitingsdatum: "Melding bij naderende sluitingsdatum",
  onboardingEvaluatie: "Onboarding & evaluatie",
  klantadresGeocoderenPDOK: "Klantadres geocoderen (PDOK)",
  klantadressenGeocoderenBulkPDOK: "Klantadressen geocoderen — bulk (PDOK)",
  locatieadresGeocoderenPDOK: "Locatieadres geocoderen (PDOK)",
  locatieadressenGeocoderenBulkPDOK: "Locatieadressen geocoderen — bulk (PDOK)",
  vacatureadresGeocoderenPDOK: "Vacatureadres geocoderen (PDOK)",
  vacatureadressenGeocoderenBulkPDOK: "Vacatureadressen geocoderen — bulk (PDOK)",
  nieuweMatchMelding: "Nieuwe match — melding",
  opMatchfaseMelding: "Op matchfase — melding",
  whatsappStoringMelding: "WhatsApp-storing — melding",
  whatsappHersteldMelding: "WhatsApp hersteld — melding",
  afwijzingMelding: "Afwijzing — melding",
  verlopendDocumentMelding: "Verlopend document — melding",
  ontbrekendeCVMelding: "Ontbrekende CV — melding",
  onbeantwoordGesprekMelding: "Onbeantwoord gesprek — melding",
  bijnaWeerBeschikbaarMelding: "Bijna weer beschikbaar — melding",
  bijnaWeerBeschikbaarTaak: "Bijna weer beschikbaar — taak",
  beschikbaarheidsdatumVerstrekenMelding: "Beschikbaarheidsdatum verstreken — melding",
  beschikbaarheidsdatumVerstrekenTaak: "Beschikbaarheidsdatum verstreken — taak",
  verlofLooptBijnaAfMelding: "Verlof loopt bijna af — melding",
  verlofLooptBijnaAfTaak: "Verlof loopt bijna af — taak",
  verlofdatumVerstrekenMelding: "Verlofdatum verstreken — melding",
  verlofdatumVerstrekenTaak: "Verlofdatum verstreken — taak",
  nietBeschikbaarPeriodeLooptBijnaAfMelding: "Niet-beschikbaar-periode loopt bijna af — melding",
  nietBeschikbaarPeriodeLooptBijnaAfTaak: "Niet-beschikbaar-periode loopt bijna af — taak",
  nietBeschikbaarDatumVerstrekenMelding: "Niet-beschikbaar-datum verstreken — melding",
  nietBeschikbaarDatumVerstrekenTaak: "Niet-beschikbaar-datum verstreken — taak",
  staatStilOpStatusMelding: "Staat stil op status — melding",
  staatStilOpStatusTaak: "Staat stil op status — taak",
  leadStaatStilMelding: "Lead staat stil — melding",
  leadStaatStilTaak: "Lead staat stil — taak",
  langGeenContactBellijst: "Lang geen contact → bellijst",
  langGeenContactWhatsAppCheckIn: "Lang geen contact → WhatsApp check-in",
  langNietGesprokenMelding: "Lang niet gesproken — melding",
  vraagBewaartoestemming: "Vraag bewaartoestemming",
  verloopMeldingBewaartermijn: "Verloop-melding bewaartermijn",
  archiveerBijVerlopenBewaartermijn: "Archiveer bij verlopen bewaartermijn",
  escalatieDossierStaatTeLangGearchiveerd: "Escalatie: dossier staat te lang gearchiveerd",
  backofficeMailenBijArchivering: "Backoffice mailen bij archivering",
  aiPlannerEmployeeStatusChange: "AI Planner - Employee status change",
  aiPlannerOfferingShiftsActiefNIEUW: "AI Planner - Offering Shifts - Actief - NIEUW",
  aiPlannerOfferingShiftsActief: "AI Planner - Offering Shifts - Actief",
  aiPlannerOfferingShiftsNietActief: "AI Planner - Offering Shifts - Niet actief",
  aiPlannerOfferingShiftsIntake: "AI Planner - Offering Shifts - Intake",
  aiPlannerShiftReminder: "AI Planner - ShiftReminder",
  aiPlannerGeenReactie2472u: "AI Planner - Geen reactie (24-72u)",
  aiPlannerGeenReactieEscalatie72u: "AI Planner - Geen reactie escalatie (>72u)",
  aiPlannerWorkedShifts: "AI Planner - Worked Shifts",
  aiPlannerResponse: "AI Planner - Response",
  aiRecruiterPaktNieuweSollicitatieOp: "AI-recruiter pakt nieuwe sollicitatie op",
  syncAlles: "Sync alles",
  syncKandidaten: "Sync kandidaten",
  syncKlanten: "Sync klanten",
  syncDiensten: "Sync diensten",
  aiPlannerDeEscalate: "AI Planner De-Escalate",
  smElanza: "SM → Elanza",
  elanzaSM: "Elanza → SM",
  aelioSMPRD: "Aelio → SM - PRD",
  smAelio: "SM → Aelio",
  aelioCheckOutHours: "Aelio - Check-Out Hours",
  aelioFLEXDETASM: "Aelio FLEX/DETA → SM",
  intusSM: "Intus → SM",
  smIntus: "SM → Intus",
  intusSMGewerkteDiensttijden: "Intus → SM Gewerkte diensttijden",
  sdbBeschikbaarMailhook: "SDB Beschikbaar Mailhook",
  sdbVervallenMailhook: "SDB Vervallen Mailhook",
  smSDBPlanning: "SM → SDB Planning",
  nightlyKandidaatVerrijking: "Nightly kandidaat-verrijking",
  // ROUND 2 (25-08): the six Koios AI action templates (KoiosAiTemplateSeeder,
  // seeded ACTIVE into the koios_ai folder for every tenant) were missing here —
  // measured live via the koios_ai folder on #aiagents.
  koiosVerstuurWhatsApp: "Koios: verstuur WhatsApp",
  koiosVerstuurEMail: "Koios: verstuur e-mail",
  koiosMaakTaak: "Koios: maak taak",
  koiosPlanAfspraak: "Koios: plan afspraak",
  koiosStuurNotificatie: "Koios: stuur notificatie",
  koiosVoegToeAanBellijst: "Koios: voeg toe aan bellijst",
}

// Merged into SEED_LABELS (lookupSeedCatalogue.ts) under the same two keys.
export const WORKFLOW_SEED_LABELS: Record<string, Record<string, string>> = {
  workflowFolders,
  workflowNames,
}
