/**
 * demoSeedTexts/de — DEMO-SEED-TAAL-1: display-only translations of the DEMO
 * tenant's seeded free texts (candidate profile summaries, vacancy descriptions,
 * customer company texts). Keys are the NORMALIZED Dutch source text (trim +
 * collapse inner whitespace, see useSeedText in ./index.ts); values are the
 * faithful German translation, generated from e2e/demo-text-inventory.json.
 * A tenant edit no longer matches a key, so edited text always wins — see index.ts.
 * Re-run scratchpad gen script after a re-harvest to keep this file in sync.
 * Convention: Dutch qualification codes (N4, IG, Plus, EVV'er) stay verbatim; sector abbreviations (GHZ) are expanded per language.
 */
const catalogue: Record<string, string> = {
  "Action DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Action DC ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Ahmed is een ervaren logistiek medewerker uit Amsterdam.": "Ahmed hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Ahmed is een ervaren logistiek medewerker uit Den Haag.": "Ahmed hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Ahmed is een ervaren logistiek medewerker uit Eindhoven.": "Ahmed hat Erfahrung in der Logistik und kommt aus Eindhoven.",
  "Ahmed is een ervaren logistiek medewerker uit Groningen.": "Ahmed hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Albert Heijn DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Albert Heijn DC ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Amira is een ervaren logistiek medewerker uit Amsterdam.": "Amira hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Amira is een ervaren logistiek medewerker uit Groningen.": "Amira hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Amira is een ervaren logistiek medewerker uit Haarlem.": "Amira hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Amira is een ervaren logistiek medewerker uit Utrecht.": "Amira hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Anouk is een ervaren logistiek medewerker uit Amsterdam.": "Anouk hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Anouk is een ervaren logistiek medewerker uit Breda.": "Anouk hat Erfahrung in der Logistik und kommt aus Breda.",
  "Anouk is een ervaren logistiek medewerker uit Eindhoven.": "Anouk hat Erfahrung in der Logistik und kommt aus Eindhoven.",
  "Anouk is een ervaren logistiek medewerker uit Groningen.": "Anouk hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Anouk is een ervaren logistiek medewerker uit Haarlem.": "Anouk hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Anouk is een ervaren logistiek medewerker uit Rotterdam.": "Anouk hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "Bakker Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bakker Logistiek ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Bol Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bol Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Bram is een ervaren logistiek medewerker uit Amsterdam.": "Bram hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Bram is een ervaren logistiek medewerker uit Breda.": "Bram hat Erfahrung in der Logistik und kommt aus Breda.",
  "Bram is een ervaren logistiek medewerker uit Den Haag.": "Bram hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Bram is een ervaren logistiek medewerker uit Haarlem.": "Bram hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Bram is een ervaren logistiek medewerker uit Rotterdam.": "Bram hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "CEVA Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "CEVA Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Coolblue Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Coolblue Logistiek ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "DB Schenker is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DB Schenker ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "DHL Supply Chain is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DHL Supply Chain ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "DSV Solutions is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DSV Solutions ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Demo-vacature voor Activiteitenbegeleider. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Aktivitätenbetreuer. Generiert für Testdaten.",
  "Demo-vacature voor Ambulant begeleider. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Ambulanter Betreuer. Generiert für Testdaten.",
  "Demo-vacature voor Begeleider GHZ. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Betreuer Behindertenhilfe. Generiert für Testdaten.",
  "Demo-vacature voor Doktersassistent. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Arzthelfer. Generiert für Testdaten.",
  "Demo-vacature voor EVV'er. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für EVV'er. Generiert für Testdaten.",
  "Demo-vacature voor Helpende Plus. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Pflegehelfer Plus. Generiert für Testdaten.",
  "Demo-vacature voor Verpleegkundige N4. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Pflegefachkraft N4. Generiert für Testdaten.",
  "Demo-vacature voor Verzorgende IG. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Pflegefachassistent IG. Generiert für Testdaten.",
  "Demo-vacature voor Wijkverpleegkundige. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Bezirkspflegekraft. Generiert für Testdaten.",
  "Demo-vacature voor Woonbegeleider. Gegenereerd voor test-data.": "Demo-Stellenausschreibung für Wohnbegleiter. Generiert für Testdaten.",
  "Esmee is een ervaren logistiek medewerker uit Breda.": "Esmee hat Erfahrung in der Logistik und kommt aus Breda.",
  "Esmee is een ervaren logistiek medewerker uit Den Haag.": "Esmee hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Esmee is een ervaren logistiek medewerker uit Rotterdam.": "Esmee hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "Esmee is een ervaren logistiek medewerker uit Utrecht.": "Esmee hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Eva is een ervaren logistiek medewerker uit Den Haag.": "Eva hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Eva is een ervaren logistiek medewerker uit Haarlem.": "Eva hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Femke is een ervaren logistiek medewerker uit Breda.": "Femke hat Erfahrung in der Logistik und kommt aus Breda.",
  "GXO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "GXO Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Ines is een ervaren logistiek medewerker uit Den Haag.": "Ines hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Ines is een ervaren logistiek medewerker uit Haarlem.": "Ines hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Ines is een ervaren logistiek medewerker uit Utrecht.": "Ines hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Jesse is een ervaren logistiek medewerker uit Amsterdam.": "Jesse hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Jesse is een ervaren logistiek medewerker uit Breda.": "Jesse hat Erfahrung in der Logistik und kommt aus Breda.",
  "Jesse is een ervaren logistiek medewerker uit Haarlem.": "Jesse hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Jumbo Distributie is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Jumbo Distributie ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Kevin is een ervaren logistiek medewerker uit Den Haag.": "Kevin hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Kevin is een ervaren logistiek medewerker uit Eindhoven.": "Kevin hat Erfahrung in der Logistik und kommt aus Eindhoven.",
  "Kevin is een ervaren logistiek medewerker uit Groningen.": "Kevin hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Kevin is een ervaren logistiek medewerker uit Haarlem.": "Kevin hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Kevin is een ervaren logistiek medewerker uit Rotterdam.": "Kevin hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "Kuehne+Nagel is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Kuehne+Nagel ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Lars is een ervaren logistiek medewerker uit Amsterdam.": "Lars hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Lars is een ervaren logistiek medewerker uit Breda.": "Lars hat Erfahrung in der Logistik und kommt aus Breda.",
  "Lars is een ervaren logistiek medewerker uit Den Haag.": "Lars hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Lars is een ervaren logistiek medewerker uit Utrecht.": "Lars hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Lidl Nederland is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Lidl Nederland ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Mert is een ervaren logistiek medewerker uit Den Haag.": "Mert hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Mert is een ervaren logistiek medewerker uit Eindhoven.": "Mert hat Erfahrung in der Logistik und kommt aus Eindhoven.",
  "Mert is een ervaren logistiek medewerker uit Utrecht.": "Mert hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Milan is een ervaren logistiek medewerker uit Breda.": "Milan hat Erfahrung in der Logistik und kommt aus Breda.",
  "Milan is een ervaren logistiek medewerker uit Groningen.": "Milan hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Milan is een ervaren logistiek medewerker uit Haarlem.": "Milan hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Nabuurs is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Nabuurs ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Nora is een ervaren logistiek medewerker uit Amsterdam.": "Nora hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Nora is een ervaren logistiek medewerker uit Den Haag.": "Nora hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Nora is een ervaren logistiek medewerker uit Groningen.": "Nora hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Nora is een ervaren logistiek medewerker uit Haarlem.": "Nora hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Nora is een ervaren logistiek medewerker uit Rotterdam.": "Nora hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "Nora is een ervaren logistiek medewerker uit Utrecht.": "Nora hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Picnic is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Picnic ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "PostNL Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "PostNL Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Priya is een ervaren logistiek medewerker uit Breda.": "Priya hat Erfahrung in der Logistik und kommt aus Breda.",
  "Priya is een ervaren logistiek medewerker uit Eindhoven.": "Priya hat Erfahrung in der Logistik und kommt aus Eindhoven.",
  "Priya is een ervaren logistiek medewerker uit Groningen.": "Priya hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Priya is een ervaren logistiek medewerker uit Haarlem.": "Priya hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Rhenus Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Rhenus Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Ruben is een ervaren logistiek medewerker uit Breda.": "Ruben hat Erfahrung in der Logistik und kommt aus Breda.",
  "Ruben is een ervaren logistiek medewerker uit Den Haag.": "Ruben hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Ruben is een ervaren logistiek medewerker uit Groningen.": "Ruben hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Simon Loos is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Simon Loos ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Sofia is een ervaren logistiek medewerker uit Breda.": "Sofia hat Erfahrung in der Logistik und kommt aus Breda.",
  "Sofia is een ervaren logistiek medewerker uit Haarlem.": "Sofia hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Amsterdam.": "Thijs hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Thijs is een ervaren logistiek medewerker uit Haarlem.": "Thijs hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Rotterdam.": "Thijs hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "Thijs is een ervaren logistiek medewerker uit Utrecht.": "Thijs hat Erfahrung in der Logistik und kommt aus Utrecht.",
  "Tim is een ervaren logistiek medewerker uit Amsterdam.": "Tim hat Erfahrung in der Logistik und kommt aus Amsterdam.",
  "Tim is een ervaren logistiek medewerker uit Breda.": "Tim hat Erfahrung in der Logistik und kommt aus Breda.",
  "Tim is een ervaren logistiek medewerker uit Den Haag.": "Tim hat Erfahrung in der Logistik und kommt aus Den Haag.",
  "Tim is een ervaren logistiek medewerker uit Haarlem.": "Tim hat Erfahrung in der Logistik und kommt aus Haarlem.",
  "Tim is een ervaren logistiek medewerker uit Rotterdam.": "Tim hat Erfahrung in der Logistik und kommt aus Rotterdam.",
  "Vos Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Vos Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "XPO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "XPO Logistics ist ein Logistikdienstleister und fester Kunde.\n\n## Schreibstil\nGeschäftlich und direkt\n\n## Rekrutierungsprobleme\nSpitzenbelastung erfordert einen schnellen Zustrom an Flexkräften.",
  "Zoë is een ervaren logistiek medewerker uit Groningen.": "Zoë hat Erfahrung in der Logistik und kommt aus Groningen.",
  "Zoë is een ervaren logistiek medewerker uit Utrecht.": "Zoë hat Erfahrung in der Logistik und kommt aus Utrecht.",
}

export default catalogue
