/**
 * demoSeedTexts/en — DEMO-SEED-TAAL-1: display-only translations of the DEMO
 * tenant's seeded free texts (candidate profile summaries, vacancy descriptions,
 * customer company texts). Keys are the NORMALIZED Dutch source text (trim +
 * collapse inner whitespace, see useSeedText in ./index.ts); values are the
 * faithful English translation, generated from e2e/demo-text-inventory.json.
 * A tenant edit no longer matches a key, so edited text always wins — see index.ts.
 * Re-run scratchpad gen script after a re-harvest to keep this file in sync.
 * Convention: Dutch qualification codes (N4, IG, Plus, EVV'er) stay verbatim; sector abbreviations (GHZ) are expanded per language.
 */
const catalogue: Record<string, string> = {
  "Action DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Action DC is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Ahmed is een ervaren logistiek medewerker uit Amsterdam.": "Ahmed is an experienced logistics worker from Amsterdam.",
  "Ahmed is een ervaren logistiek medewerker uit Den Haag.": "Ahmed is an experienced logistics worker from Den Haag.",
  "Ahmed is een ervaren logistiek medewerker uit Eindhoven.": "Ahmed is an experienced logistics worker from Eindhoven.",
  "Ahmed is een ervaren logistiek medewerker uit Groningen.": "Ahmed is an experienced logistics worker from Groningen.",
  "Albert Heijn DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Albert Heijn DC is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Amira is een ervaren logistiek medewerker uit Amsterdam.": "Amira is an experienced logistics worker from Amsterdam.",
  "Amira is een ervaren logistiek medewerker uit Groningen.": "Amira is an experienced logistics worker from Groningen.",
  "Amira is een ervaren logistiek medewerker uit Haarlem.": "Amira is an experienced logistics worker from Haarlem.",
  "Amira is een ervaren logistiek medewerker uit Utrecht.": "Amira is an experienced logistics worker from Utrecht.",
  "Anouk is een ervaren logistiek medewerker uit Amsterdam.": "Anouk is an experienced logistics worker from Amsterdam.",
  "Anouk is een ervaren logistiek medewerker uit Breda.": "Anouk is an experienced logistics worker from Breda.",
  "Anouk is een ervaren logistiek medewerker uit Eindhoven.": "Anouk is an experienced logistics worker from Eindhoven.",
  "Anouk is een ervaren logistiek medewerker uit Groningen.": "Anouk is an experienced logistics worker from Groningen.",
  "Anouk is een ervaren logistiek medewerker uit Haarlem.": "Anouk is an experienced logistics worker from Haarlem.",
  "Anouk is een ervaren logistiek medewerker uit Rotterdam.": "Anouk is an experienced logistics worker from Rotterdam.",
  "Bakker Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bakker Logistiek is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Bol Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bol Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Bram is een ervaren logistiek medewerker uit Amsterdam.": "Bram is an experienced logistics worker from Amsterdam.",
  "Bram is een ervaren logistiek medewerker uit Breda.": "Bram is an experienced logistics worker from Breda.",
  "Bram is een ervaren logistiek medewerker uit Den Haag.": "Bram is an experienced logistics worker from Den Haag.",
  "Bram is een ervaren logistiek medewerker uit Haarlem.": "Bram is an experienced logistics worker from Haarlem.",
  "Bram is een ervaren logistiek medewerker uit Rotterdam.": "Bram is an experienced logistics worker from Rotterdam.",
  "CEVA Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "CEVA Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Coolblue Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Coolblue Logistiek is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "DB Schenker is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DB Schenker is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "DHL Supply Chain is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DHL Supply Chain is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "DSV Solutions is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DSV Solutions is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Demo-vacature voor Activiteitenbegeleider. Gegenereerd voor test-data.": "Demo vacancy for Activity Coordinator. Generated for test data.",
  "Demo-vacature voor Ambulant begeleider. Gegenereerd voor test-data.": "Demo vacancy for Outreach Support Worker. Generated for test data.",
  "Demo-vacature voor Begeleider GHZ. Gegenereerd voor test-data.": "Demo vacancy for Disability Support Worker. Generated for test data.",
  "Demo-vacature voor Doktersassistent. Gegenereerd voor test-data.": "Demo vacancy for Medical Assistant. Generated for test data.",
  "Demo-vacature voor EVV'er. Gegenereerd voor test-data.": "Demo vacancy for EVV'er. Generated for test data.",
  "Demo-vacature voor Helpende Plus. Gegenereerd voor test-data.": "Demo vacancy for Care Helper Plus. Generated for test data.",
  "Demo-vacature voor Verpleegkundige N4. Gegenereerd voor test-data.": "Demo vacancy for Nurse N4. Generated for test data.",
  "Demo-vacature voor Verzorgende IG. Gegenereerd voor test-data.": "Demo vacancy for Care Worker IG. Generated for test data.",
  "Demo-vacature voor Wijkverpleegkundige. Gegenereerd voor test-data.": "Demo vacancy for District Nurse. Generated for test data.",
  "Demo-vacature voor Woonbegeleider. Gegenereerd voor test-data.": "Demo vacancy for Residential Support Worker. Generated for test data.",
  "Esmee is een ervaren logistiek medewerker uit Breda.": "Esmee is an experienced logistics worker from Breda.",
  "Esmee is een ervaren logistiek medewerker uit Den Haag.": "Esmee is an experienced logistics worker from Den Haag.",
  "Esmee is een ervaren logistiek medewerker uit Rotterdam.": "Esmee is an experienced logistics worker from Rotterdam.",
  "Esmee is een ervaren logistiek medewerker uit Utrecht.": "Esmee is an experienced logistics worker from Utrecht.",
  "Eva is een ervaren logistiek medewerker uit Den Haag.": "Eva is an experienced logistics worker from Den Haag.",
  "Eva is een ervaren logistiek medewerker uit Haarlem.": "Eva is an experienced logistics worker from Haarlem.",
  "Femke is een ervaren logistiek medewerker uit Breda.": "Femke is an experienced logistics worker from Breda.",
  "GXO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "GXO Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Ines is een ervaren logistiek medewerker uit Den Haag.": "Ines is an experienced logistics worker from Den Haag.",
  "Ines is een ervaren logistiek medewerker uit Haarlem.": "Ines is an experienced logistics worker from Haarlem.",
  "Ines is een ervaren logistiek medewerker uit Utrecht.": "Ines is an experienced logistics worker from Utrecht.",
  "Jesse is een ervaren logistiek medewerker uit Amsterdam.": "Jesse is an experienced logistics worker from Amsterdam.",
  "Jesse is een ervaren logistiek medewerker uit Breda.": "Jesse is an experienced logistics worker from Breda.",
  "Jesse is een ervaren logistiek medewerker uit Haarlem.": "Jesse is an experienced logistics worker from Haarlem.",
  "Jumbo Distributie is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Jumbo Distributie is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Kevin is een ervaren logistiek medewerker uit Den Haag.": "Kevin is an experienced logistics worker from Den Haag.",
  "Kevin is een ervaren logistiek medewerker uit Eindhoven.": "Kevin is an experienced logistics worker from Eindhoven.",
  "Kevin is een ervaren logistiek medewerker uit Groningen.": "Kevin is an experienced logistics worker from Groningen.",
  "Kevin is een ervaren logistiek medewerker uit Haarlem.": "Kevin is an experienced logistics worker from Haarlem.",
  "Kevin is een ervaren logistiek medewerker uit Rotterdam.": "Kevin is an experienced logistics worker from Rotterdam.",
  "Kuehne+Nagel is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Kuehne+Nagel is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Lars is een ervaren logistiek medewerker uit Amsterdam.": "Lars is an experienced logistics worker from Amsterdam.",
  "Lars is een ervaren logistiek medewerker uit Breda.": "Lars is an experienced logistics worker from Breda.",
  "Lars is een ervaren logistiek medewerker uit Den Haag.": "Lars is an experienced logistics worker from Den Haag.",
  "Lars is een ervaren logistiek medewerker uit Utrecht.": "Lars is an experienced logistics worker from Utrecht.",
  "Lidl Nederland is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Lidl Nederland is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Mert is een ervaren logistiek medewerker uit Den Haag.": "Mert is an experienced logistics worker from Den Haag.",
  "Mert is een ervaren logistiek medewerker uit Eindhoven.": "Mert is an experienced logistics worker from Eindhoven.",
  "Mert is een ervaren logistiek medewerker uit Utrecht.": "Mert is an experienced logistics worker from Utrecht.",
  "Milan is een ervaren logistiek medewerker uit Breda.": "Milan is an experienced logistics worker from Breda.",
  "Milan is een ervaren logistiek medewerker uit Groningen.": "Milan is an experienced logistics worker from Groningen.",
  "Milan is een ervaren logistiek medewerker uit Haarlem.": "Milan is an experienced logistics worker from Haarlem.",
  "Nabuurs is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Nabuurs is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Nora is een ervaren logistiek medewerker uit Amsterdam.": "Nora is an experienced logistics worker from Amsterdam.",
  "Nora is een ervaren logistiek medewerker uit Den Haag.": "Nora is an experienced logistics worker from Den Haag.",
  "Nora is een ervaren logistiek medewerker uit Groningen.": "Nora is an experienced logistics worker from Groningen.",
  "Nora is een ervaren logistiek medewerker uit Haarlem.": "Nora is an experienced logistics worker from Haarlem.",
  "Nora is een ervaren logistiek medewerker uit Rotterdam.": "Nora is an experienced logistics worker from Rotterdam.",
  "Nora is een ervaren logistiek medewerker uit Utrecht.": "Nora is an experienced logistics worker from Utrecht.",
  "Picnic is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Picnic is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "PostNL Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "PostNL Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Priya is een ervaren logistiek medewerker uit Breda.": "Priya is an experienced logistics worker from Breda.",
  "Priya is een ervaren logistiek medewerker uit Eindhoven.": "Priya is an experienced logistics worker from Eindhoven.",
  "Priya is een ervaren logistiek medewerker uit Groningen.": "Priya is an experienced logistics worker from Groningen.",
  "Priya is een ervaren logistiek medewerker uit Haarlem.": "Priya is an experienced logistics worker from Haarlem.",
  "Rhenus Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Rhenus Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Ruben is een ervaren logistiek medewerker uit Breda.": "Ruben is an experienced logistics worker from Breda.",
  "Ruben is een ervaren logistiek medewerker uit Den Haag.": "Ruben is an experienced logistics worker from Den Haag.",
  "Ruben is een ervaren logistiek medewerker uit Groningen.": "Ruben is an experienced logistics worker from Groningen.",
  "Simon Loos is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Simon Loos is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Sofia is een ervaren logistiek medewerker uit Breda.": "Sofia is an experienced logistics worker from Breda.",
  "Sofia is een ervaren logistiek medewerker uit Haarlem.": "Sofia is an experienced logistics worker from Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Amsterdam.": "Thijs is an experienced logistics worker from Amsterdam.",
  "Thijs is een ervaren logistiek medewerker uit Haarlem.": "Thijs is an experienced logistics worker from Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Rotterdam.": "Thijs is an experienced logistics worker from Rotterdam.",
  "Thijs is een ervaren logistiek medewerker uit Utrecht.": "Thijs is an experienced logistics worker from Utrecht.",
  "Tim is een ervaren logistiek medewerker uit Amsterdam.": "Tim is an experienced logistics worker from Amsterdam.",
  "Tim is een ervaren logistiek medewerker uit Breda.": "Tim is an experienced logistics worker from Breda.",
  "Tim is een ervaren logistiek medewerker uit Den Haag.": "Tim is an experienced logistics worker from Den Haag.",
  "Tim is een ervaren logistiek medewerker uit Haarlem.": "Tim is an experienced logistics worker from Haarlem.",
  "Tim is een ervaren logistiek medewerker uit Rotterdam.": "Tim is an experienced logistics worker from Rotterdam.",
  "Vos Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Vos Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "XPO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "XPO Logistics is a logistics provider and regular customer.\n\n## Writing style\nProfessional and direct\n\n## Recruitment challenges\nPeak demand requires a fast influx of flex workers.",
  "Zoë is een ervaren logistiek medewerker uit Groningen.": "Zoë is an experienced logistics worker from Groningen.",
  "Zoë is een ervaren logistiek medewerker uit Utrecht.": "Zoë is an experienced logistics worker from Utrecht.",
}

export default catalogue
