/**
 * demoSeedTexts/es — DEMO-SEED-TAAL-1: display-only translations of the DEMO
 * tenant's seeded free texts (candidate profile summaries, vacancy descriptions,
 * customer company texts). Keys are the NORMALIZED Dutch source text (trim +
 * collapse inner whitespace, see useSeedText in ./index.ts); values are the
 * faithful Spanish translation, generated from e2e/demo-text-inventory.json.
 * A tenant edit no longer matches a key, so edited text always wins — see index.ts.
 * Re-run scratchpad gen script after a re-harvest to keep this file in sync.
 * Convention: Dutch qualification codes (N4, IG, Plus, EVV'er) stay verbatim; sector abbreviations (GHZ) are expanded per language.
 */
const catalogue: Record<string, string> = {
  "Action DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Action DC es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Ahmed is een ervaren logistiek medewerker uit Amsterdam.": "Ahmed cuenta con experiencia en logística y es de Amsterdam.",
  "Ahmed is een ervaren logistiek medewerker uit Den Haag.": "Ahmed cuenta con experiencia en logística y es de Den Haag.",
  "Ahmed is een ervaren logistiek medewerker uit Eindhoven.": "Ahmed cuenta con experiencia en logística y es de Eindhoven.",
  "Ahmed is een ervaren logistiek medewerker uit Groningen.": "Ahmed cuenta con experiencia en logística y es de Groningen.",
  "Albert Heijn DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Albert Heijn DC es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Amira is een ervaren logistiek medewerker uit Amsterdam.": "Amira cuenta con experiencia en logística y es de Amsterdam.",
  "Amira is een ervaren logistiek medewerker uit Groningen.": "Amira cuenta con experiencia en logística y es de Groningen.",
  "Amira is een ervaren logistiek medewerker uit Haarlem.": "Amira cuenta con experiencia en logística y es de Haarlem.",
  "Amira is een ervaren logistiek medewerker uit Utrecht.": "Amira cuenta con experiencia en logística y es de Utrecht.",
  "Anouk is een ervaren logistiek medewerker uit Amsterdam.": "Anouk cuenta con experiencia en logística y es de Amsterdam.",
  "Anouk is een ervaren logistiek medewerker uit Breda.": "Anouk cuenta con experiencia en logística y es de Breda.",
  "Anouk is een ervaren logistiek medewerker uit Eindhoven.": "Anouk cuenta con experiencia en logística y es de Eindhoven.",
  "Anouk is een ervaren logistiek medewerker uit Groningen.": "Anouk cuenta con experiencia en logística y es de Groningen.",
  "Anouk is een ervaren logistiek medewerker uit Haarlem.": "Anouk cuenta con experiencia en logística y es de Haarlem.",
  "Anouk is een ervaren logistiek medewerker uit Rotterdam.": "Anouk cuenta con experiencia en logística y es de Rotterdam.",
  "Bakker Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bakker Logistiek es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Bol Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bol Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Bram is een ervaren logistiek medewerker uit Amsterdam.": "Bram cuenta con experiencia en logística y es de Amsterdam.",
  "Bram is een ervaren logistiek medewerker uit Breda.": "Bram cuenta con experiencia en logística y es de Breda.",
  "Bram is een ervaren logistiek medewerker uit Den Haag.": "Bram cuenta con experiencia en logística y es de Den Haag.",
  "Bram is een ervaren logistiek medewerker uit Haarlem.": "Bram cuenta con experiencia en logística y es de Haarlem.",
  "Bram is een ervaren logistiek medewerker uit Rotterdam.": "Bram cuenta con experiencia en logística y es de Rotterdam.",
  "CEVA Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "CEVA Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Coolblue Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Coolblue Logistiek es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "DB Schenker is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DB Schenker es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "DHL Supply Chain is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DHL Supply Chain es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "DSV Solutions is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DSV Solutions es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Demo-vacature voor Activiteitenbegeleider. Gegenereerd voor test-data.": "Vacante de demostración para Coordinador de actividades. Generada para datos de prueba.",
  "Demo-vacature voor Ambulant begeleider. Gegenereerd voor test-data.": "Vacante de demostración para Acompañante ambulatorio. Generada para datos de prueba.",
  "Demo-vacature voor Begeleider GHZ. Gegenereerd voor test-data.": "Vacante de demostración para Acompañante de discapacidad. Generada para datos de prueba.",
  "Demo-vacature voor Doktersassistent. Gegenereerd voor test-data.": "Vacante de demostración para Auxiliar médico. Generada para datos de prueba.",
  "Demo-vacature voor EVV'er. Gegenereerd voor test-data.": "Vacante de demostración para EVV'er. Generada para datos de prueba.",
  "Demo-vacature voor Helpende Plus. Gegenereerd voor test-data.": "Vacante de demostración para Auxiliar de cuidados Plus. Generada para datos de prueba.",
  "Demo-vacature voor Verpleegkundige N4. Gegenereerd voor test-data.": "Vacante de demostración para Enfermero N4. Generada para datos de prueba.",
  "Demo-vacature voor Verzorgende IG. Gegenereerd voor test-data.": "Vacante de demostración para Técnico en cuidados IG. Generada para datos de prueba.",
  "Demo-vacature voor Wijkverpleegkundige. Gegenereerd voor test-data.": "Vacante de demostración para Enfermero comunitario. Generada para datos de prueba.",
  "Demo-vacature voor Woonbegeleider. Gegenereerd voor test-data.": "Vacante de demostración para Acompañante residencial. Generada para datos de prueba.",
  "Esmee is een ervaren logistiek medewerker uit Breda.": "Esmee cuenta con experiencia en logística y es de Breda.",
  "Esmee is een ervaren logistiek medewerker uit Den Haag.": "Esmee cuenta con experiencia en logística y es de Den Haag.",
  "Esmee is een ervaren logistiek medewerker uit Rotterdam.": "Esmee cuenta con experiencia en logística y es de Rotterdam.",
  "Esmee is een ervaren logistiek medewerker uit Utrecht.": "Esmee cuenta con experiencia en logística y es de Utrecht.",
  "Eva is een ervaren logistiek medewerker uit Den Haag.": "Eva cuenta con experiencia en logística y es de Den Haag.",
  "Eva is een ervaren logistiek medewerker uit Haarlem.": "Eva cuenta con experiencia en logística y es de Haarlem.",
  "Femke is een ervaren logistiek medewerker uit Breda.": "Femke cuenta con experiencia en logística y es de Breda.",
  "GXO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "GXO Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Ines is een ervaren logistiek medewerker uit Den Haag.": "Ines cuenta con experiencia en logística y es de Den Haag.",
  "Ines is een ervaren logistiek medewerker uit Haarlem.": "Ines cuenta con experiencia en logística y es de Haarlem.",
  "Ines is een ervaren logistiek medewerker uit Utrecht.": "Ines cuenta con experiencia en logística y es de Utrecht.",
  "Jesse is een ervaren logistiek medewerker uit Amsterdam.": "Jesse cuenta con experiencia en logística y es de Amsterdam.",
  "Jesse is een ervaren logistiek medewerker uit Breda.": "Jesse cuenta con experiencia en logística y es de Breda.",
  "Jesse is een ervaren logistiek medewerker uit Haarlem.": "Jesse cuenta con experiencia en logística y es de Haarlem.",
  "Jumbo Distributie is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Jumbo Distributie es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Kevin is een ervaren logistiek medewerker uit Den Haag.": "Kevin cuenta con experiencia en logística y es de Den Haag.",
  "Kevin is een ervaren logistiek medewerker uit Eindhoven.": "Kevin cuenta con experiencia en logística y es de Eindhoven.",
  "Kevin is een ervaren logistiek medewerker uit Groningen.": "Kevin cuenta con experiencia en logística y es de Groningen.",
  "Kevin is een ervaren logistiek medewerker uit Haarlem.": "Kevin cuenta con experiencia en logística y es de Haarlem.",
  "Kevin is een ervaren logistiek medewerker uit Rotterdam.": "Kevin cuenta con experiencia en logística y es de Rotterdam.",
  "Kuehne+Nagel is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Kuehne+Nagel es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Lars is een ervaren logistiek medewerker uit Amsterdam.": "Lars cuenta con experiencia en logística y es de Amsterdam.",
  "Lars is een ervaren logistiek medewerker uit Breda.": "Lars cuenta con experiencia en logística y es de Breda.",
  "Lars is een ervaren logistiek medewerker uit Den Haag.": "Lars cuenta con experiencia en logística y es de Den Haag.",
  "Lars is een ervaren logistiek medewerker uit Utrecht.": "Lars cuenta con experiencia en logística y es de Utrecht.",
  "Lidl Nederland is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Lidl Nederland es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Mert is een ervaren logistiek medewerker uit Den Haag.": "Mert cuenta con experiencia en logística y es de Den Haag.",
  "Mert is een ervaren logistiek medewerker uit Eindhoven.": "Mert cuenta con experiencia en logística y es de Eindhoven.",
  "Mert is een ervaren logistiek medewerker uit Utrecht.": "Mert cuenta con experiencia en logística y es de Utrecht.",
  "Milan is een ervaren logistiek medewerker uit Breda.": "Milan cuenta con experiencia en logística y es de Breda.",
  "Milan is een ervaren logistiek medewerker uit Groningen.": "Milan cuenta con experiencia en logística y es de Groningen.",
  "Milan is een ervaren logistiek medewerker uit Haarlem.": "Milan cuenta con experiencia en logística y es de Haarlem.",
  "Nabuurs is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Nabuurs es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Nora is een ervaren logistiek medewerker uit Amsterdam.": "Nora cuenta con experiencia en logística y es de Amsterdam.",
  "Nora is een ervaren logistiek medewerker uit Den Haag.": "Nora cuenta con experiencia en logística y es de Den Haag.",
  "Nora is een ervaren logistiek medewerker uit Groningen.": "Nora cuenta con experiencia en logística y es de Groningen.",
  "Nora is een ervaren logistiek medewerker uit Haarlem.": "Nora cuenta con experiencia en logística y es de Haarlem.",
  "Nora is een ervaren logistiek medewerker uit Rotterdam.": "Nora cuenta con experiencia en logística y es de Rotterdam.",
  "Nora is een ervaren logistiek medewerker uit Utrecht.": "Nora cuenta con experiencia en logística y es de Utrecht.",
  "Picnic is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Picnic es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "PostNL Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "PostNL Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Priya is een ervaren logistiek medewerker uit Breda.": "Priya cuenta con experiencia en logística y es de Breda.",
  "Priya is een ervaren logistiek medewerker uit Eindhoven.": "Priya cuenta con experiencia en logística y es de Eindhoven.",
  "Priya is een ervaren logistiek medewerker uit Groningen.": "Priya cuenta con experiencia en logística y es de Groningen.",
  "Priya is een ervaren logistiek medewerker uit Haarlem.": "Priya cuenta con experiencia en logística y es de Haarlem.",
  "Rhenus Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Rhenus Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Ruben is een ervaren logistiek medewerker uit Breda.": "Ruben cuenta con experiencia en logística y es de Breda.",
  "Ruben is een ervaren logistiek medewerker uit Den Haag.": "Ruben cuenta con experiencia en logística y es de Den Haag.",
  "Ruben is een ervaren logistiek medewerker uit Groningen.": "Ruben cuenta con experiencia en logística y es de Groningen.",
  "Simon Loos is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Simon Loos es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Sofia is een ervaren logistiek medewerker uit Breda.": "Sofia cuenta con experiencia en logística y es de Breda.",
  "Sofia is een ervaren logistiek medewerker uit Haarlem.": "Sofia cuenta con experiencia en logística y es de Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Amsterdam.": "Thijs cuenta con experiencia en logística y es de Amsterdam.",
  "Thijs is een ervaren logistiek medewerker uit Haarlem.": "Thijs cuenta con experiencia en logística y es de Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Rotterdam.": "Thijs cuenta con experiencia en logística y es de Rotterdam.",
  "Thijs is een ervaren logistiek medewerker uit Utrecht.": "Thijs cuenta con experiencia en logística y es de Utrecht.",
  "Tim is een ervaren logistiek medewerker uit Amsterdam.": "Tim cuenta con experiencia en logística y es de Amsterdam.",
  "Tim is een ervaren logistiek medewerker uit Breda.": "Tim cuenta con experiencia en logística y es de Breda.",
  "Tim is een ervaren logistiek medewerker uit Den Haag.": "Tim cuenta con experiencia en logística y es de Den Haag.",
  "Tim is een ervaren logistiek medewerker uit Haarlem.": "Tim cuenta con experiencia en logística y es de Haarlem.",
  "Tim is een ervaren logistiek medewerker uit Rotterdam.": "Tim cuenta con experiencia en logística y es de Rotterdam.",
  "Vos Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Vos Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "XPO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "XPO Logistics es un proveedor logístico y cliente habitual.\n\n## Estilo de redacción\nProfesional y directo\n\n## Problemas de contratación\nLos picos de actividad requieren una rápida incorporación de personal flexible.",
  "Zoë is een ervaren logistiek medewerker uit Groningen.": "Zoë cuenta con experiencia en logística y es de Groningen.",
  "Zoë is een ervaren logistiek medewerker uit Utrecht.": "Zoë cuenta con experiencia en logística y es de Utrecht.",
}

export default catalogue
