/**
 * demoSeedTexts/fr — DEMO-SEED-TAAL-1: display-only translations of the DEMO
 * tenant's seeded free texts (candidate profile summaries, vacancy descriptions,
 * customer company texts). Keys are the NORMALIZED Dutch source text (trim +
 * collapse inner whitespace, see useSeedText in ./index.ts); values are the
 * faithful French translation, generated from e2e/demo-text-inventory.json.
 * A tenant edit no longer matches a key, so edited text always wins — see index.ts.
 * Re-run scratchpad gen script after a re-harvest to keep this file in sync.
 * Convention: Dutch qualification codes (N4, IG, Plus, EVV'er) stay verbatim; sector abbreviations (GHZ) are expanded per language.
 */
const catalogue: Record<string, string> = {
  "Action DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Action DC est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Ahmed is een ervaren logistiek medewerker uit Amsterdam.": "Ahmed possède une expérience en logistique et vient d'Amsterdam.",
  "Ahmed is een ervaren logistiek medewerker uit Den Haag.": "Ahmed possède une expérience en logistique et vient de Den Haag.",
  "Ahmed is een ervaren logistiek medewerker uit Eindhoven.": "Ahmed possède une expérience en logistique et vient d'Eindhoven.",
  "Ahmed is een ervaren logistiek medewerker uit Groningen.": "Ahmed possède une expérience en logistique et vient de Groningen.",
  "Albert Heijn DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Albert Heijn DC est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Amira is een ervaren logistiek medewerker uit Amsterdam.": "Amira possède une expérience en logistique et vient d'Amsterdam.",
  "Amira is een ervaren logistiek medewerker uit Groningen.": "Amira possède une expérience en logistique et vient de Groningen.",
  "Amira is een ervaren logistiek medewerker uit Haarlem.": "Amira possède une expérience en logistique et vient de Haarlem.",
  "Amira is een ervaren logistiek medewerker uit Utrecht.": "Amira possède une expérience en logistique et vient d'Utrecht.",
  "Anouk is een ervaren logistiek medewerker uit Amsterdam.": "Anouk possède une expérience en logistique et vient d'Amsterdam.",
  "Anouk is een ervaren logistiek medewerker uit Breda.": "Anouk possède une expérience en logistique et vient de Breda.",
  "Anouk is een ervaren logistiek medewerker uit Eindhoven.": "Anouk possède une expérience en logistique et vient d'Eindhoven.",
  "Anouk is een ervaren logistiek medewerker uit Groningen.": "Anouk possède une expérience en logistique et vient de Groningen.",
  "Anouk is een ervaren logistiek medewerker uit Haarlem.": "Anouk possède une expérience en logistique et vient de Haarlem.",
  "Anouk is een ervaren logistiek medewerker uit Rotterdam.": "Anouk possède une expérience en logistique et vient de Rotterdam.",
  "Bakker Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bakker Logistiek est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Bol Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bol Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Bram is een ervaren logistiek medewerker uit Amsterdam.": "Bram possède une expérience en logistique et vient d'Amsterdam.",
  "Bram is een ervaren logistiek medewerker uit Breda.": "Bram possède une expérience en logistique et vient de Breda.",
  "Bram is een ervaren logistiek medewerker uit Den Haag.": "Bram possède une expérience en logistique et vient de Den Haag.",
  "Bram is een ervaren logistiek medewerker uit Haarlem.": "Bram possède une expérience en logistique et vient de Haarlem.",
  "Bram is een ervaren logistiek medewerker uit Rotterdam.": "Bram possède une expérience en logistique et vient de Rotterdam.",
  "CEVA Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "CEVA Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Coolblue Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Coolblue Logistiek est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "DB Schenker is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DB Schenker est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "DHL Supply Chain is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DHL Supply Chain est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "DSV Solutions is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DSV Solutions est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Demo-vacature voor Activiteitenbegeleider. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Animateur d'activités. Générée pour les données de test.",
  "Demo-vacature voor Ambulant begeleider. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Accompagnant ambulatoire. Générée pour les données de test.",
  "Demo-vacature voor Begeleider GHZ. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Accompagnant handicap. Générée pour les données de test.",
  "Demo-vacature voor Doktersassistent. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Assistant médical. Générée pour les données de test.",
  "Demo-vacature voor EVV'er. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour EVV'er. Générée pour les données de test.",
  "Demo-vacature voor Helpende Plus. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Aide-soignant Plus. Générée pour les données de test.",
  "Demo-vacature voor Verpleegkundige N4. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Infirmier N4. Générée pour les données de test.",
  "Demo-vacature voor Verzorgende IG. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Aide-soignant qualifié IG. Générée pour les données de test.",
  "Demo-vacature voor Wijkverpleegkundige. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Infirmier de quartier. Générée pour les données de test.",
  "Demo-vacature voor Woonbegeleider. Gegenereerd voor test-data.": "Offre d'emploi de démonstration pour Accompagnant résidentiel. Générée pour les données de test.",
  "Esmee is een ervaren logistiek medewerker uit Breda.": "Esmee possède une expérience en logistique et vient de Breda.",
  "Esmee is een ervaren logistiek medewerker uit Den Haag.": "Esmee possède une expérience en logistique et vient de Den Haag.",
  "Esmee is een ervaren logistiek medewerker uit Rotterdam.": "Esmee possède une expérience en logistique et vient de Rotterdam.",
  "Esmee is een ervaren logistiek medewerker uit Utrecht.": "Esmee possède une expérience en logistique et vient d'Utrecht.",
  "Eva is een ervaren logistiek medewerker uit Den Haag.": "Eva possède une expérience en logistique et vient de Den Haag.",
  "Eva is een ervaren logistiek medewerker uit Haarlem.": "Eva possède une expérience en logistique et vient de Haarlem.",
  "Femke is een ervaren logistiek medewerker uit Breda.": "Femke possède une expérience en logistique et vient de Breda.",
  "GXO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "GXO Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Ines is een ervaren logistiek medewerker uit Den Haag.": "Ines possède une expérience en logistique et vient de Den Haag.",
  "Ines is een ervaren logistiek medewerker uit Haarlem.": "Ines possède une expérience en logistique et vient de Haarlem.",
  "Ines is een ervaren logistiek medewerker uit Utrecht.": "Ines possède une expérience en logistique et vient d'Utrecht.",
  "Jesse is een ervaren logistiek medewerker uit Amsterdam.": "Jesse possède une expérience en logistique et vient d'Amsterdam.",
  "Jesse is een ervaren logistiek medewerker uit Breda.": "Jesse possède une expérience en logistique et vient de Breda.",
  "Jesse is een ervaren logistiek medewerker uit Haarlem.": "Jesse possède une expérience en logistique et vient de Haarlem.",
  "Jumbo Distributie is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Jumbo Distributie est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Kevin is een ervaren logistiek medewerker uit Den Haag.": "Kevin possède une expérience en logistique et vient de Den Haag.",
  "Kevin is een ervaren logistiek medewerker uit Eindhoven.": "Kevin possède une expérience en logistique et vient d'Eindhoven.",
  "Kevin is een ervaren logistiek medewerker uit Groningen.": "Kevin possède une expérience en logistique et vient de Groningen.",
  "Kevin is een ervaren logistiek medewerker uit Haarlem.": "Kevin possède une expérience en logistique et vient de Haarlem.",
  "Kevin is een ervaren logistiek medewerker uit Rotterdam.": "Kevin possède une expérience en logistique et vient de Rotterdam.",
  "Kuehne+Nagel is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Kuehne+Nagel est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Lars is een ervaren logistiek medewerker uit Amsterdam.": "Lars possède une expérience en logistique et vient d'Amsterdam.",
  "Lars is een ervaren logistiek medewerker uit Breda.": "Lars possède une expérience en logistique et vient de Breda.",
  "Lars is een ervaren logistiek medewerker uit Den Haag.": "Lars possède une expérience en logistique et vient de Den Haag.",
  "Lars is een ervaren logistiek medewerker uit Utrecht.": "Lars possède une expérience en logistique et vient d'Utrecht.",
  "Lidl Nederland is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Lidl Nederland est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Mert is een ervaren logistiek medewerker uit Den Haag.": "Mert possède une expérience en logistique et vient de Den Haag.",
  "Mert is een ervaren logistiek medewerker uit Eindhoven.": "Mert possède une expérience en logistique et vient d'Eindhoven.",
  "Mert is een ervaren logistiek medewerker uit Utrecht.": "Mert possède une expérience en logistique et vient d'Utrecht.",
  "Milan is een ervaren logistiek medewerker uit Breda.": "Milan possède une expérience en logistique et vient de Breda.",
  "Milan is een ervaren logistiek medewerker uit Groningen.": "Milan possède une expérience en logistique et vient de Groningen.",
  "Milan is een ervaren logistiek medewerker uit Haarlem.": "Milan possède une expérience en logistique et vient de Haarlem.",
  "Nabuurs is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Nabuurs est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Nora is een ervaren logistiek medewerker uit Amsterdam.": "Nora possède une expérience en logistique et vient d'Amsterdam.",
  "Nora is een ervaren logistiek medewerker uit Den Haag.": "Nora possède une expérience en logistique et vient de Den Haag.",
  "Nora is een ervaren logistiek medewerker uit Groningen.": "Nora possède une expérience en logistique et vient de Groningen.",
  "Nora is een ervaren logistiek medewerker uit Haarlem.": "Nora possède une expérience en logistique et vient de Haarlem.",
  "Nora is een ervaren logistiek medewerker uit Rotterdam.": "Nora possède une expérience en logistique et vient de Rotterdam.",
  "Nora is een ervaren logistiek medewerker uit Utrecht.": "Nora possède une expérience en logistique et vient d'Utrecht.",
  "Picnic is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Picnic est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "PostNL Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "PostNL Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Priya is een ervaren logistiek medewerker uit Breda.": "Priya possède une expérience en logistique et vient de Breda.",
  "Priya is een ervaren logistiek medewerker uit Eindhoven.": "Priya possède une expérience en logistique et vient d'Eindhoven.",
  "Priya is een ervaren logistiek medewerker uit Groningen.": "Priya possède une expérience en logistique et vient de Groningen.",
  "Priya is een ervaren logistiek medewerker uit Haarlem.": "Priya possède une expérience en logistique et vient de Haarlem.",
  "Rhenus Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Rhenus Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Ruben is een ervaren logistiek medewerker uit Breda.": "Ruben possède une expérience en logistique et vient de Breda.",
  "Ruben is een ervaren logistiek medewerker uit Den Haag.": "Ruben possède une expérience en logistique et vient de Den Haag.",
  "Ruben is een ervaren logistiek medewerker uit Groningen.": "Ruben possède une expérience en logistique et vient de Groningen.",
  "Simon Loos is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Simon Loos est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Sofia is een ervaren logistiek medewerker uit Breda.": "Sofia possède une expérience en logistique et vient de Breda.",
  "Sofia is een ervaren logistiek medewerker uit Haarlem.": "Sofia possède une expérience en logistique et vient de Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Amsterdam.": "Thijs possède une expérience en logistique et vient d'Amsterdam.",
  "Thijs is een ervaren logistiek medewerker uit Haarlem.": "Thijs possède une expérience en logistique et vient de Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Rotterdam.": "Thijs possède une expérience en logistique et vient de Rotterdam.",
  "Thijs is een ervaren logistiek medewerker uit Utrecht.": "Thijs possède une expérience en logistique et vient d'Utrecht.",
  "Tim is een ervaren logistiek medewerker uit Amsterdam.": "Tim possède une expérience en logistique et vient d'Amsterdam.",
  "Tim is een ervaren logistiek medewerker uit Breda.": "Tim possède une expérience en logistique et vient de Breda.",
  "Tim is een ervaren logistiek medewerker uit Den Haag.": "Tim possède une expérience en logistique et vient de Den Haag.",
  "Tim is een ervaren logistiek medewerker uit Haarlem.": "Tim possède une expérience en logistique et vient de Haarlem.",
  "Tim is een ervaren logistiek medewerker uit Rotterdam.": "Tim possède une expérience en logistique et vient de Rotterdam.",
  "Vos Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Vos Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "XPO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "XPO Logistics est un prestataire logistique et un client fidèle.\n\n## Style d'écriture\nProfessionnel et direct\n\n## Problèmes de recrutement\nLes pics d'activité exigent un afflux rapide de personnel flexible.",
  "Zoë is een ervaren logistiek medewerker uit Groningen.": "Zoë possède une expérience en logistique et vient de Groningen.",
  "Zoë is een ervaren logistiek medewerker uit Utrecht.": "Zoë possède une expérience en logistique et vient d'Utrecht.",
}

export default catalogue
