/**
 * demoSeedTexts/it — DEMO-SEED-TAAL-1: display-only translations of the DEMO
 * tenant's seeded free texts (candidate profile summaries, vacancy descriptions,
 * customer company texts). Keys are the NORMALIZED Dutch source text (trim +
 * collapse inner whitespace, see useSeedText in ./index.ts); values are the
 * faithful Italian translation, generated from e2e/demo-text-inventory.json.
 * A tenant edit no longer matches a key, so edited text always wins — see index.ts.
 * Re-run scratchpad gen script after a re-harvest to keep this file in sync.
 * Convention: Dutch qualification codes (N4, IG, Plus, EVV'er) stay verbatim; sector abbreviations (GHZ) are expanded per language.
 */
const catalogue: Record<string, string> = {
  "Action DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Action DC è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Ahmed is een ervaren logistiek medewerker uit Amsterdam.": "Ahmed ha esperienza nella logistica e viene da Amsterdam.",
  "Ahmed is een ervaren logistiek medewerker uit Den Haag.": "Ahmed ha esperienza nella logistica e viene da Den Haag.",
  "Ahmed is een ervaren logistiek medewerker uit Eindhoven.": "Ahmed ha esperienza nella logistica e viene da Eindhoven.",
  "Ahmed is een ervaren logistiek medewerker uit Groningen.": "Ahmed ha esperienza nella logistica e viene da Groningen.",
  "Albert Heijn DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Albert Heijn DC è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Amira is een ervaren logistiek medewerker uit Amsterdam.": "Amira ha esperienza nella logistica e viene da Amsterdam.",
  "Amira is een ervaren logistiek medewerker uit Groningen.": "Amira ha esperienza nella logistica e viene da Groningen.",
  "Amira is een ervaren logistiek medewerker uit Haarlem.": "Amira ha esperienza nella logistica e viene da Haarlem.",
  "Amira is een ervaren logistiek medewerker uit Utrecht.": "Amira ha esperienza nella logistica e viene da Utrecht.",
  "Anouk is een ervaren logistiek medewerker uit Amsterdam.": "Anouk ha esperienza nella logistica e viene da Amsterdam.",
  "Anouk is een ervaren logistiek medewerker uit Breda.": "Anouk ha esperienza nella logistica e viene da Breda.",
  "Anouk is een ervaren logistiek medewerker uit Eindhoven.": "Anouk ha esperienza nella logistica e viene da Eindhoven.",
  "Anouk is een ervaren logistiek medewerker uit Groningen.": "Anouk ha esperienza nella logistica e viene da Groningen.",
  "Anouk is een ervaren logistiek medewerker uit Haarlem.": "Anouk ha esperienza nella logistica e viene da Haarlem.",
  "Anouk is een ervaren logistiek medewerker uit Rotterdam.": "Anouk ha esperienza nella logistica e viene da Rotterdam.",
  "Bakker Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bakker Logistiek è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Bol Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bol Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Bram is een ervaren logistiek medewerker uit Amsterdam.": "Bram ha esperienza nella logistica e viene da Amsterdam.",
  "Bram is een ervaren logistiek medewerker uit Breda.": "Bram ha esperienza nella logistica e viene da Breda.",
  "Bram is een ervaren logistiek medewerker uit Den Haag.": "Bram ha esperienza nella logistica e viene da Den Haag.",
  "Bram is een ervaren logistiek medewerker uit Haarlem.": "Bram ha esperienza nella logistica e viene da Haarlem.",
  "Bram is een ervaren logistiek medewerker uit Rotterdam.": "Bram ha esperienza nella logistica e viene da Rotterdam.",
  "CEVA Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "CEVA Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Coolblue Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Coolblue Logistiek è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "DB Schenker is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DB Schenker è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "DHL Supply Chain is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DHL Supply Chain è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "DSV Solutions is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DSV Solutions è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Demo-vacature voor Activiteitenbegeleider. Gegenereerd voor test-data.": "Offerta di lavoro demo per Animatore Attività. Generata per dati di test.",
  "Demo-vacature voor Ambulant begeleider. Gegenereerd voor test-data.": "Offerta di lavoro demo per Assistente Ambulatoriale. Generata per dati di test.",
  "Demo-vacature voor Begeleider GHZ. Gegenereerd voor test-data.": "Offerta di lavoro demo per Assistente per la Disabilità. Generata per dati di test.",
  "Demo-vacature voor Doktersassistent. Gegenereerd voor test-data.": "Offerta di lavoro demo per Assistente Medico. Generata per dati di test.",
  "Demo-vacature voor EVV'er. Gegenereerd voor test-data.": "Offerta di lavoro demo per EVV'er. Generata per dati di test.",
  "Demo-vacature voor Helpende Plus. Gegenereerd voor test-data.": "Offerta di lavoro demo per Assistente di Cura Plus. Generata per dati di test.",
  "Demo-vacature voor Verpleegkundige N4. Gegenereerd voor test-data.": "Offerta di lavoro demo per Infermiere N4. Generata per dati di test.",
  "Demo-vacature voor Verzorgende IG. Gegenereerd voor test-data.": "Offerta di lavoro demo per Assistente di Cura IG. Generata per dati di test.",
  "Demo-vacature voor Wijkverpleegkundige. Gegenereerd voor test-data.": "Offerta di lavoro demo per Infermiere di Quartiere. Generata per dati di test.",
  "Demo-vacature voor Woonbegeleider. Gegenereerd voor test-data.": "Offerta di lavoro demo per Assistente Abitativo. Generata per dati di test.",
  "Esmee is een ervaren logistiek medewerker uit Breda.": "Esmee ha esperienza nella logistica e viene da Breda.",
  "Esmee is een ervaren logistiek medewerker uit Den Haag.": "Esmee ha esperienza nella logistica e viene da Den Haag.",
  "Esmee is een ervaren logistiek medewerker uit Rotterdam.": "Esmee ha esperienza nella logistica e viene da Rotterdam.",
  "Esmee is een ervaren logistiek medewerker uit Utrecht.": "Esmee ha esperienza nella logistica e viene da Utrecht.",
  "Eva is een ervaren logistiek medewerker uit Den Haag.": "Eva ha esperienza nella logistica e viene da Den Haag.",
  "Eva is een ervaren logistiek medewerker uit Haarlem.": "Eva ha esperienza nella logistica e viene da Haarlem.",
  "Femke is een ervaren logistiek medewerker uit Breda.": "Femke ha esperienza nella logistica e viene da Breda.",
  "GXO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "GXO Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Ines is een ervaren logistiek medewerker uit Den Haag.": "Ines ha esperienza nella logistica e viene da Den Haag.",
  "Ines is een ervaren logistiek medewerker uit Haarlem.": "Ines ha esperienza nella logistica e viene da Haarlem.",
  "Ines is een ervaren logistiek medewerker uit Utrecht.": "Ines ha esperienza nella logistica e viene da Utrecht.",
  "Jesse is een ervaren logistiek medewerker uit Amsterdam.": "Jesse ha esperienza nella logistica e viene da Amsterdam.",
  "Jesse is een ervaren logistiek medewerker uit Breda.": "Jesse ha esperienza nella logistica e viene da Breda.",
  "Jesse is een ervaren logistiek medewerker uit Haarlem.": "Jesse ha esperienza nella logistica e viene da Haarlem.",
  "Jumbo Distributie is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Jumbo Distributie è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Kevin is een ervaren logistiek medewerker uit Den Haag.": "Kevin ha esperienza nella logistica e viene da Den Haag.",
  "Kevin is een ervaren logistiek medewerker uit Eindhoven.": "Kevin ha esperienza nella logistica e viene da Eindhoven.",
  "Kevin is een ervaren logistiek medewerker uit Groningen.": "Kevin ha esperienza nella logistica e viene da Groningen.",
  "Kevin is een ervaren logistiek medewerker uit Haarlem.": "Kevin ha esperienza nella logistica e viene da Haarlem.",
  "Kevin is een ervaren logistiek medewerker uit Rotterdam.": "Kevin ha esperienza nella logistica e viene da Rotterdam.",
  "Kuehne+Nagel is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Kuehne+Nagel è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Lars is een ervaren logistiek medewerker uit Amsterdam.": "Lars ha esperienza nella logistica e viene da Amsterdam.",
  "Lars is een ervaren logistiek medewerker uit Breda.": "Lars ha esperienza nella logistica e viene da Breda.",
  "Lars is een ervaren logistiek medewerker uit Den Haag.": "Lars ha esperienza nella logistica e viene da Den Haag.",
  "Lars is een ervaren logistiek medewerker uit Utrecht.": "Lars ha esperienza nella logistica e viene da Utrecht.",
  "Lidl Nederland is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Lidl Nederland è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Mert is een ervaren logistiek medewerker uit Den Haag.": "Mert ha esperienza nella logistica e viene da Den Haag.",
  "Mert is een ervaren logistiek medewerker uit Eindhoven.": "Mert ha esperienza nella logistica e viene da Eindhoven.",
  "Mert is een ervaren logistiek medewerker uit Utrecht.": "Mert ha esperienza nella logistica e viene da Utrecht.",
  "Milan is een ervaren logistiek medewerker uit Breda.": "Milan ha esperienza nella logistica e viene da Breda.",
  "Milan is een ervaren logistiek medewerker uit Groningen.": "Milan ha esperienza nella logistica e viene da Groningen.",
  "Milan is een ervaren logistiek medewerker uit Haarlem.": "Milan ha esperienza nella logistica e viene da Haarlem.",
  "Nabuurs is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Nabuurs è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Nora is een ervaren logistiek medewerker uit Amsterdam.": "Nora ha esperienza nella logistica e viene da Amsterdam.",
  "Nora is een ervaren logistiek medewerker uit Den Haag.": "Nora ha esperienza nella logistica e viene da Den Haag.",
  "Nora is een ervaren logistiek medewerker uit Groningen.": "Nora ha esperienza nella logistica e viene da Groningen.",
  "Nora is een ervaren logistiek medewerker uit Haarlem.": "Nora ha esperienza nella logistica e viene da Haarlem.",
  "Nora is een ervaren logistiek medewerker uit Rotterdam.": "Nora ha esperienza nella logistica e viene da Rotterdam.",
  "Nora is een ervaren logistiek medewerker uit Utrecht.": "Nora ha esperienza nella logistica e viene da Utrecht.",
  "Picnic is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Picnic è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "PostNL Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "PostNL Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Priya is een ervaren logistiek medewerker uit Breda.": "Priya ha esperienza nella logistica e viene da Breda.",
  "Priya is een ervaren logistiek medewerker uit Eindhoven.": "Priya ha esperienza nella logistica e viene da Eindhoven.",
  "Priya is een ervaren logistiek medewerker uit Groningen.": "Priya ha esperienza nella logistica e viene da Groningen.",
  "Priya is een ervaren logistiek medewerker uit Haarlem.": "Priya ha esperienza nella logistica e viene da Haarlem.",
  "Rhenus Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Rhenus Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Ruben is een ervaren logistiek medewerker uit Breda.": "Ruben ha esperienza nella logistica e viene da Breda.",
  "Ruben is een ervaren logistiek medewerker uit Den Haag.": "Ruben ha esperienza nella logistica e viene da Den Haag.",
  "Ruben is een ervaren logistiek medewerker uit Groningen.": "Ruben ha esperienza nella logistica e viene da Groningen.",
  "Simon Loos is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Simon Loos è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Sofia is een ervaren logistiek medewerker uit Breda.": "Sofia ha esperienza nella logistica e viene da Breda.",
  "Sofia is een ervaren logistiek medewerker uit Haarlem.": "Sofia ha esperienza nella logistica e viene da Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Amsterdam.": "Thijs ha esperienza nella logistica e viene da Amsterdam.",
  "Thijs is een ervaren logistiek medewerker uit Haarlem.": "Thijs ha esperienza nella logistica e viene da Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Rotterdam.": "Thijs ha esperienza nella logistica e viene da Rotterdam.",
  "Thijs is een ervaren logistiek medewerker uit Utrecht.": "Thijs ha esperienza nella logistica e viene da Utrecht.",
  "Tim is een ervaren logistiek medewerker uit Amsterdam.": "Tim ha esperienza nella logistica e viene da Amsterdam.",
  "Tim is een ervaren logistiek medewerker uit Breda.": "Tim ha esperienza nella logistica e viene da Breda.",
  "Tim is een ervaren logistiek medewerker uit Den Haag.": "Tim ha esperienza nella logistica e viene da Den Haag.",
  "Tim is een ervaren logistiek medewerker uit Haarlem.": "Tim ha esperienza nella logistica e viene da Haarlem.",
  "Tim is een ervaren logistiek medewerker uit Rotterdam.": "Tim ha esperienza nella logistica e viene da Rotterdam.",
  "Vos Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Vos Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "XPO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "XPO Logistics è un fornitore di servizi logistici e cliente fisso.\n\n## Stile di scrittura\nProfessionale e diretto\n\n## Difficoltà di reclutamento\nI picchi di attività richiedono un rapido afflusso di personale flessibile.",
  "Zoë is een ervaren logistiek medewerker uit Groningen.": "Zoë ha esperienza nella logistica e viene da Groningen.",
  "Zoë is een ervaren logistiek medewerker uit Utrecht.": "Zoë ha esperienza nella logistica e viene da Utrecht.",
}

export default catalogue
