/**
 * demoSeedTexts/pt — DEMO-SEED-TAAL-1: display-only translations of the DEMO
 * tenant's seeded free texts (candidate profile summaries, vacancy descriptions,
 * customer company texts). Keys are the NORMALIZED Dutch source text (trim +
 * collapse inner whitespace, see useSeedText in ./index.ts); values are the
 * faithful Portuguese translation, generated from e2e/demo-text-inventory.json.
 * A tenant edit no longer matches a key, so edited text always wins — see index.ts.
 * Re-run scratchpad gen script after a re-harvest to keep this file in sync.
 * Convention: Dutch qualification codes (N4, IG, Plus, EVV'er) stay verbatim; sector abbreviations (GHZ) are expanded per language.
 */
const catalogue: Record<string, string> = {
  "Action DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Action DC é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Ahmed is een ervaren logistiek medewerker uit Amsterdam.": "Ahmed tem experiência em logística e vem de Amsterdam.",
  "Ahmed is een ervaren logistiek medewerker uit Den Haag.": "Ahmed tem experiência em logística e vem de Den Haag.",
  "Ahmed is een ervaren logistiek medewerker uit Eindhoven.": "Ahmed tem experiência em logística e vem de Eindhoven.",
  "Ahmed is een ervaren logistiek medewerker uit Groningen.": "Ahmed tem experiência em logística e vem de Groningen.",
  "Albert Heijn DC is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Albert Heijn DC é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Amira is een ervaren logistiek medewerker uit Amsterdam.": "Amira tem experiência em logística e vem de Amsterdam.",
  "Amira is een ervaren logistiek medewerker uit Groningen.": "Amira tem experiência em logística e vem de Groningen.",
  "Amira is een ervaren logistiek medewerker uit Haarlem.": "Amira tem experiência em logística e vem de Haarlem.",
  "Amira is een ervaren logistiek medewerker uit Utrecht.": "Amira tem experiência em logística e vem de Utrecht.",
  "Anouk is een ervaren logistiek medewerker uit Amsterdam.": "Anouk tem experiência em logística e vem de Amsterdam.",
  "Anouk is een ervaren logistiek medewerker uit Breda.": "Anouk tem experiência em logística e vem de Breda.",
  "Anouk is een ervaren logistiek medewerker uit Eindhoven.": "Anouk tem experiência em logística e vem de Eindhoven.",
  "Anouk is een ervaren logistiek medewerker uit Groningen.": "Anouk tem experiência em logística e vem de Groningen.",
  "Anouk is een ervaren logistiek medewerker uit Haarlem.": "Anouk tem experiência em logística e vem de Haarlem.",
  "Anouk is een ervaren logistiek medewerker uit Rotterdam.": "Anouk tem experiência em logística e vem de Rotterdam.",
  "Bakker Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bakker Logistiek é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Bol Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Bol Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Bram is een ervaren logistiek medewerker uit Amsterdam.": "Bram tem experiência em logística e vem de Amsterdam.",
  "Bram is een ervaren logistiek medewerker uit Breda.": "Bram tem experiência em logística e vem de Breda.",
  "Bram is een ervaren logistiek medewerker uit Den Haag.": "Bram tem experiência em logística e vem de Den Haag.",
  "Bram is een ervaren logistiek medewerker uit Haarlem.": "Bram tem experiência em logística e vem de Haarlem.",
  "Bram is een ervaren logistiek medewerker uit Rotterdam.": "Bram tem experiência em logística e vem de Rotterdam.",
  "CEVA Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "CEVA Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Coolblue Logistiek is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Coolblue Logistiek é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "DB Schenker is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DB Schenker é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "DHL Supply Chain is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DHL Supply Chain é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "DSV Solutions is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "DSV Solutions é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Demo-vacature voor Activiteitenbegeleider. Gegenereerd voor test-data.": "Vaga de demonstração para Assistente de Atividades. Gerada para dados de teste.",
  "Demo-vacature voor Ambulant begeleider. Gegenereerd voor test-data.": "Vaga de demonstração para Acompanhante Ambulatorial. Gerada para dados de teste.",
  "Demo-vacature voor Begeleider GHZ. Gegenereerd voor test-data.": "Vaga de demonstração para Assistente de Deficiência. Gerada para dados de teste.",
  "Demo-vacature voor Doktersassistent. Gegenereerd voor test-data.": "Vaga de demonstração para Assistente Médico. Gerada para dados de teste.",
  "Demo-vacature voor EVV'er. Gegenereerd voor test-data.": "Vaga de demonstração para EVV'er. Gerada para dados de teste.",
  "Demo-vacature voor Helpende Plus. Gegenereerd voor test-data.": "Vaga de demonstração para Auxiliar de Cuidados Plus. Gerada para dados de teste.",
  "Demo-vacature voor Verpleegkundige N4. Gegenereerd voor test-data.": "Vaga de demonstração para Enfermeiro N4. Gerada para dados de teste.",
  "Demo-vacature voor Verzorgende IG. Gegenereerd voor test-data.": "Vaga de demonstração para Auxiliar de Enfermagem IG. Gerada para dados de teste.",
  "Demo-vacature voor Wijkverpleegkundige. Gegenereerd voor test-data.": "Vaga de demonstração para Enfermeiro Comunitário. Gerada para dados de teste.",
  "Demo-vacature voor Woonbegeleider. Gegenereerd voor test-data.": "Vaga de demonstração para Assistente Residencial. Gerada para dados de teste.",
  "Esmee is een ervaren logistiek medewerker uit Breda.": "Esmee tem experiência em logística e vem de Breda.",
  "Esmee is een ervaren logistiek medewerker uit Den Haag.": "Esmee tem experiência em logística e vem de Den Haag.",
  "Esmee is een ervaren logistiek medewerker uit Rotterdam.": "Esmee tem experiência em logística e vem de Rotterdam.",
  "Esmee is een ervaren logistiek medewerker uit Utrecht.": "Esmee tem experiência em logística e vem de Utrecht.",
  "Eva is een ervaren logistiek medewerker uit Den Haag.": "Eva tem experiência em logística e vem de Den Haag.",
  "Eva is een ervaren logistiek medewerker uit Haarlem.": "Eva tem experiência em logística e vem de Haarlem.",
  "Femke is een ervaren logistiek medewerker uit Breda.": "Femke tem experiência em logística e vem de Breda.",
  "GXO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "GXO Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Ines is een ervaren logistiek medewerker uit Den Haag.": "Ines tem experiência em logística e vem de Den Haag.",
  "Ines is een ervaren logistiek medewerker uit Haarlem.": "Ines tem experiência em logística e vem de Haarlem.",
  "Ines is een ervaren logistiek medewerker uit Utrecht.": "Ines tem experiência em logística e vem de Utrecht.",
  "Jesse is een ervaren logistiek medewerker uit Amsterdam.": "Jesse tem experiência em logística e vem de Amsterdam.",
  "Jesse is een ervaren logistiek medewerker uit Breda.": "Jesse tem experiência em logística e vem de Breda.",
  "Jesse is een ervaren logistiek medewerker uit Haarlem.": "Jesse tem experiência em logística e vem de Haarlem.",
  "Jumbo Distributie is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Jumbo Distributie é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Kevin is een ervaren logistiek medewerker uit Den Haag.": "Kevin tem experiência em logística e vem de Den Haag.",
  "Kevin is een ervaren logistiek medewerker uit Eindhoven.": "Kevin tem experiência em logística e vem de Eindhoven.",
  "Kevin is een ervaren logistiek medewerker uit Groningen.": "Kevin tem experiência em logística e vem de Groningen.",
  "Kevin is een ervaren logistiek medewerker uit Haarlem.": "Kevin tem experiência em logística e vem de Haarlem.",
  "Kevin is een ervaren logistiek medewerker uit Rotterdam.": "Kevin tem experiência em logística e vem de Rotterdam.",
  "Kuehne+Nagel is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Kuehne+Nagel é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Lars is een ervaren logistiek medewerker uit Amsterdam.": "Lars tem experiência em logística e vem de Amsterdam.",
  "Lars is een ervaren logistiek medewerker uit Breda.": "Lars tem experiência em logística e vem de Breda.",
  "Lars is een ervaren logistiek medewerker uit Den Haag.": "Lars tem experiência em logística e vem de Den Haag.",
  "Lars is een ervaren logistiek medewerker uit Utrecht.": "Lars tem experiência em logística e vem de Utrecht.",
  "Lidl Nederland is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Lidl Nederland é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Mert is een ervaren logistiek medewerker uit Den Haag.": "Mert tem experiência em logística e vem de Den Haag.",
  "Mert is een ervaren logistiek medewerker uit Eindhoven.": "Mert tem experiência em logística e vem de Eindhoven.",
  "Mert is een ervaren logistiek medewerker uit Utrecht.": "Mert tem experiência em logística e vem de Utrecht.",
  "Milan is een ervaren logistiek medewerker uit Breda.": "Milan tem experiência em logística e vem de Breda.",
  "Milan is een ervaren logistiek medewerker uit Groningen.": "Milan tem experiência em logística e vem de Groningen.",
  "Milan is een ervaren logistiek medewerker uit Haarlem.": "Milan tem experiência em logística e vem de Haarlem.",
  "Nabuurs is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Nabuurs é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Nora is een ervaren logistiek medewerker uit Amsterdam.": "Nora tem experiência em logística e vem de Amsterdam.",
  "Nora is een ervaren logistiek medewerker uit Den Haag.": "Nora tem experiência em logística e vem de Den Haag.",
  "Nora is een ervaren logistiek medewerker uit Groningen.": "Nora tem experiência em logística e vem de Groningen.",
  "Nora is een ervaren logistiek medewerker uit Haarlem.": "Nora tem experiência em logística e vem de Haarlem.",
  "Nora is een ervaren logistiek medewerker uit Rotterdam.": "Nora tem experiência em logística e vem de Rotterdam.",
  "Nora is een ervaren logistiek medewerker uit Utrecht.": "Nora tem experiência em logística e vem de Utrecht.",
  "Picnic is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Picnic é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "PostNL Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "PostNL Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Priya is een ervaren logistiek medewerker uit Breda.": "Priya tem experiência em logística e vem de Breda.",
  "Priya is een ervaren logistiek medewerker uit Eindhoven.": "Priya tem experiência em logística e vem de Eindhoven.",
  "Priya is een ervaren logistiek medewerker uit Groningen.": "Priya tem experiência em logística e vem de Groningen.",
  "Priya is een ervaren logistiek medewerker uit Haarlem.": "Priya tem experiência em logística e vem de Haarlem.",
  "Rhenus Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Rhenus Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Ruben is een ervaren logistiek medewerker uit Breda.": "Ruben tem experiência em logística e vem de Breda.",
  "Ruben is een ervaren logistiek medewerker uit Den Haag.": "Ruben tem experiência em logística e vem de Den Haag.",
  "Ruben is een ervaren logistiek medewerker uit Groningen.": "Ruben tem experiência em logística e vem de Groningen.",
  "Simon Loos is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Simon Loos é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Sofia is een ervaren logistiek medewerker uit Breda.": "Sofia tem experiência em logística e vem de Breda.",
  "Sofia is een ervaren logistiek medewerker uit Haarlem.": "Sofia tem experiência em logística e vem de Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Amsterdam.": "Thijs tem experiência em logística e vem de Amsterdam.",
  "Thijs is een ervaren logistiek medewerker uit Haarlem.": "Thijs tem experiência em logística e vem de Haarlem.",
  "Thijs is een ervaren logistiek medewerker uit Rotterdam.": "Thijs tem experiência em logística e vem de Rotterdam.",
  "Thijs is een ervaren logistiek medewerker uit Utrecht.": "Thijs tem experiência em logística e vem de Utrecht.",
  "Tim is een ervaren logistiek medewerker uit Amsterdam.": "Tim tem experiência em logística e vem de Amsterdam.",
  "Tim is een ervaren logistiek medewerker uit Breda.": "Tim tem experiência em logística e vem de Breda.",
  "Tim is een ervaren logistiek medewerker uit Den Haag.": "Tim tem experiência em logística e vem de Den Haag.",
  "Tim is een ervaren logistiek medewerker uit Haarlem.": "Tim tem experiência em logística e vem de Haarlem.",
  "Tim is een ervaren logistiek medewerker uit Rotterdam.": "Tim tem experiência em logística e vem de Rotterdam.",
  "Vos Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "Vos Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "XPO Logistics is een logistiek dienstverlener en vaste klant. ## Schrijfstijl Zakelijk en direct ## Wervingsproblemen Piekdrukte vraagt om snelle flexinstroom.": "XPO Logistics é um prestador de serviços de logística e cliente fixo.\n\n## Estilo de redação\nProfissional e direto\n\n## Dificuldades de recrutamento\nOs picos de atividade exigem um rápido influxo de trabalhadores flexíveis.",
  "Zoë is een ervaren logistiek medewerker uit Groningen.": "Zoë tem experiência em logística e vem de Groningen.",
  "Zoë is een ervaren logistiek medewerker uit Utrecht.": "Zoë tem experiência em logística e vem de Utrecht.",
}

export default catalogue
